### ISSUE TITLE
could not install dotcopter on osx

### ISSUE THREAD

**Issue by codingberlin** [bomgar/dotcopter#1]
```2017-04-06 15:49:40 sbauer@isdeblnnm150 ~  » cargo install dotcopter          
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `dotcopter v0.1.1`, intermediate artifacts can be found at `/var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/cargo-install.SIxvIbNfIFpA`

To learn more, run the command again with --verbose.
2017-04-06 15:50:13 sbauer@isdeblnnm150 ~  » ll /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/cargo-install.SIxvIbNfIFpA                                               101 ⏎
total 0
drwxr-xr-x   2 sbauer  ISCOUT\admins    68B  6 Apr 15:50 ./
drwx------  98 sbauer  ISCOUT\admins   3,3K  6 Apr 15:50 ../
2017-04-06 15:51:08 sbauer@isdeblnnm150 ~  » cargo install dotcopter --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `dotcopter v0.1.1`, intermediate artifacts can be found at `/var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/cargo-install.fnk7t2CLPwed`

Caused by:
  could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
2017-04-06 15:51:22 sbauer@isdeblnnm150 ~  » cargo install --verbose dotcopter                                                                                            101 ⏎
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `dotcopter v0.1.1`, intermediate artifacts can be found at `/var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/cargo-install.pnn3dQMK2qfJ`

Caused by:
  could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
2017-04-06 15:51:35 sbauer@isdeblnnm150 ~  » cargo --verbose install dotcopter                                                                                            101 ⏎
error: Invalid arguments.

Usage:
    cargo <command> [<args>...]
    cargo [options]
```

**Comment by codingberlin** [comment]
```
2017-04-06 15:56:05 sbauer@isdeblnnm150 ~  » rustc --version                                                                                                              127 ⏎
zsh: command not found: rustc```

**Comment by codingberlin** [comment]
I installed cargo via:
```brew install Caskroom/cask/cargo```

**Comment by bomgar** [comment]
https://www.rust-lang.org/en-US/install.html

**Comment by bomgar** [comment]
Dir fehlt der Rust Compiler

**Comment by mriehl** [comment]
`brew install rust` also works and is probably preferred

**Comment by codingberlin** [comment]
After running `brew install rust` I get still:
```
2017-04-06 16:12:06 sbauer@isdeblnnm150 ~  » rustc --version
zsh: command not found: rustc```

**Comment by codingberlin** [comment]
Running https://www.rust-lang.org/en-US/install.html yields into:
```
2017-04-06 16:13:40 sbauer@isdeblnnm150 ~  » curl https://sh.rustup.rs -sSf | sh
info: downloading installer
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
note: Run with `RUST_BACKTRACE=1` for a backtrace.
rustup: command failed: /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/tmp.wA53bIgM/rustup-init
2017-04-06 16:14:10 sbauer@isdeblnnm150 ~  » ll /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/tmp.wA53bIgM/rustup-init                                                   1 ⏎
ls: /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/tmp.wA53bIgM/rustup-init: No such file or directory```

**Comment by bomgar** [comment]
Could you try to remove the brew versions before installing it with rustup?

**Comment by codingberlin** [comment]
Same
```
2017-04-06 16:23:16 sbauer@isdeblnnm150 ~  » curl https://sh.rustup.rs -sSf | sh
info: downloading installer
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
note: Run with `RUST_BACKTRACE=1` for a backtrace.
rustup: command failed: /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/tmp.7PSt8Jd5/rustup-init
```

Also the mentioned restart at the website did not help

**Comment by mriehl** [comment]
Here's the code from self_update: https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-cli/self_update.rs#L495

**Comment by mriehl** [comment]
You could try running `RUST_BACKTRACE=1 curl https://.......`

**Comment by mriehl** [comment]
It's trying to find out which rcfile it has to update (`.zshrc`, `.bashrc`, `.profile`, etc) and you have either none at all or more than 1. What shell are you using?

**Comment by codingberlin** [comment]
Yes I have `.zshrc` and `.profile` ... I run zsh shell

**Comment by mriehl** [comment]
Do you have a `.zprofile` too?

**Comment by codingberlin** [comment]
no

**Comment by mriehl** [comment]
Anything come out of running with `RUST_BACKTRACE=1` set like suggested above?

**Comment by codingberlin** [comment]
Nothing more then known
```
2017-04-06 16:35:01 sbauer@isdeblnnm150 ~  » RUST_BACKTRACE=1 curl https://sh.rustup.rs -sSf | sh
info: downloading installer
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
note: Run with `RUST_BACKTRACE=1` for a backtrace.
rustup: command failed: /var/folders/g0/swbpjncs2578kpxk2x48_1640017t6/T/tmp.Tk3NNWWB/rustup-init
```

**Comment by mriehl** [comment]
Ah but the `sh` doesn't keep the env variable.
Can you try using https://github.com/mriehl/dotfiles/blob/master/bin/rustup.sh instead?

eG `wget -O rust.sh https://raw.githubusercontent.com/mriehl/dotfiles/master/bin/rustup.sh` and then `sh rust.sh`?

**Comment by codingberlin** [comment]
This helped
```
2017-04-06 16:48:04 sbauer@isdeblnnm150 ~  » wget -O rust.sh https://raw.githubusercontent.com/mriehl/dotfiles/master/bin/rustup.sh                                       130 ⏎
--2017-04-06 16:48:05--  https://raw.githubusercontent.com/mriehl/dotfiles/master/bin/rustup.sh
Resolving raw.githubusercontent.com... 151.101.112.133
Connecting to raw.githubusercontent.com|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61986 (61K) [text/plain]
Saving to: ‘rust.sh’

rust.sh                                     100%[===========================================================================================>]  60.53K   301KB/s    in 0.2s

2017-04-06 16:48:06 (301 KB/s) - ‘rust.sh’ saved [61986/61986]

2017-04-06 16:48:06 sbauer@isdeblnnm150 ~  » sh rust.sh
Password:
rustup: gpg not available. signatures will not be verified
rustup: downloading manifest for 'stable'
rustup: downloading toolchain for 'stable'
######################################################################## 100,0%
rustup: installing toolchain for 'stable'
rustup: extracting installer
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-apple-darwin'
install: installing component 'rust-docs'
install: installing component 'cargo'

    Rust is ready to roll.

sh rust.sh  3,94s user 5,38s system 10% cpu 1:26,00 total
2017-04-06 16:49:40 sbauer@isdeblnnm150 ~  » rustc --version
rustc 1.16.0 (30cf806ef 2017-03-10)
```

**Comment by mriehl** [comment]
Nice, `cargo install` should work now too

**Comment by codingberlin** [comment]
Yes it worked. I can run dotcopter now.
```
2017-04-06 16:57:26 sbauer@isdeblnnm150 ~  » dotcopter --help                                                                                                             101 ⏎
dotcopter 0.1
Patrick Haun <bomgar85@googlemail.com>
manages dotfiles installation

USAGE:
    dotcopter [FLAGS] <config_file>

FLAGS:
    -f, --force
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v, --verbose    debug output

ARGS:
    <config_file>
```
